services:
  dev:
    image: dev-elixir:latest
    volumes:
      - .:/app
      - /home/shaine/.config/nvim:/home/dev/.config/nvim
      - /home/shaine/.config/atuin:/home/dev/.config/atuin
      - /home/shaine/.agignore:/home/dev/.agignore:ro
      - /home/shaine/.fzf:/home/dev/.fzf:ro
      - /home/shaine/.zshrc:/home/dev/.zshrc:ro
      - /home/shaine/.tmux.conf:/home/dev/.tmux.conf:ro
      - /home/shaine/.oh-my-zsh:/home/dev/.oh-my-zsh:ro
      - /home/shaine/.omz-custom:/home/dev/.omz-custom:ro
      - /home/shaine/.gitconfig:/home/dev/.gitconfig:ro
      - /home/shaine/.ssh:/home/dev/.ssh:ro
      - /home/shaine/.atuin:/home/dev/.atuin
      - /home/shaine/.local/share/atuin:/home/dev/.local/share/atuin
    depends_on:
      - db
    command: ["/entrypoint.sh"]
    ports:
      - "3999:4000"
    environment:
      - CONTAINER_NAME=${CONTAINER_NAME}
      - LANG=C.UTF-8
    user: 1000:1000

  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
